### PR TITLE
Fixed Sound Issue

### PR DESCRIPTION
**Pull request by spaghettiosareyummy**
This PR is to fix issue #31 .  

This issue was caused by pygame being unable to read the .ogg files that contained the sounds. To combat this, I converted the files into the WAV format. 

I've tested on Mac, Linux, and Windows, all seem to work perfectly!

### CODE REVIEW

**Review by R0merol — COMMENTED** [review]
I've tested it out and it works! But now there's the issue of the sound files getting too big. WAV format tends to be very big, I've checked the sound file and it alone uses up to 77 MB now. Can you convert it to another format, such as mp3 (I think I tried mp3 before and it didn't work, but maybe I was doing it wrong) or other formats that are smaller in size?

**Comment by spaghettiosareyummy** [comment]
> I've tested it out and it works! But now there's the issue of the sound files getting too big. WAV format tends to be very big, I've checked the sound file and it alone uses up to 77 MB now. Can you convert it to another format, such as mp3 (I think I tried mp3 before and it didn't work, but maybe I was doing it wrong) or other formats that are smaller in size?

I did try mp3 before attempting WAV and it didn't work properly. I will try to find another file format that is smaller.

**Comment by spaghettiosareyummy** [comment]
Pygame currently only supports mp3, ogg, and WAV. WAV is the only one that works out of the three.

**Comment by R0merol** [comment]
Is it possible to compress the WAV files further?

**Comment by spaghettiosareyummy** [comment]
Apologies for the delay in my responses, I have managed to compress the WAV files to be much smaller than they were originally. To my knowledge, this hasn't sacrificed sound quality at all.

**Review by R0merol — COMMENTED** [review]
The original sound file using .ogg was 5 MB big, using .wav, it's now 28 MB big. Not only that, but after the compression, the sound quality changed significantly. The quality of .ogg was better but I supposed using .wav will have to do for now as a temporary fix.

**Pull request merged**
