### PR TITLE
impl automated formatting and import sorting

### PR DESCRIPTION
**Pull request by colderinit**
# Implementation of isort and Black Formatting
Hi there! 👋 This pr is designed to address issue #42. I manually formatted and sorted each file. I implemented a test to verify. 

In short, I added a check if all files are sorted and formatted, and I added a vscode config to suggest any developer with the workspace open to set up isort and black formatting. 

## Checklist

- [x] test if game runs
- [x] Implement Github Actions iSort and Black formatting. 
- [x] Implement Vscode suggestions for black and isort extensions
- [x] Format code (done per commit)

## Goal

The goal of this branch is to implement two modes of **isort and Black formatting**.
1. "Checks"
2. Traditional

The "checks" mode is administered via the Github action. This [action](.github/workflows/clean-up.yml) will run Isort and Black formatting on every python file inside the `src` directory. This will return an error if there are any formatting errors or sorting errors. The badge looks like this: 
image

> This could be useful for pull requests from developers who do not have isort and black set up.

The "traditional" mode is the implementation of the VSCode extension suggestions. When the workspace is opened in vs code, the editor will check if the iSort and black formatting extensions are installed. If they are not installed, it will provide a prompt for the developer.

<details>
<summary>This is what it looks like when everything passes and there are no formatting or sorting errors!</summary>
image
</details>

### CODE REVIEW

**Comment by R0merol** [comment]
Looks awesome! I'm testing it out right now

**Comment by R0merol** [comment]
Can you resolve the conflicts?

**Comment by colderinit** [comment]
Whoops 🤦, I forgot to mention @R0merol, I updated the `./code` directory to `./src`. If you would like me to revert it, please let me know. It may help with #9.

**Comment by R0merol** [comment]
Strange, it seems like the linting cannot recognize pygame on my end
image

**Comment by colderinit** [comment]
Make sure that the python environment you use has the correct requirements installed. 
However, pylint was not initially requested in the issue, and is not necessary. Pylint is kinda like a perfectionist format. It opens up the pep rulebook and starts searching for issues. The bottom line is that pylint *usually* will complain about stuff that won't inhibit the code running, and that if it bugs you, you can turn it off. 
I highly recommend developing with pylint, so I included it in the suggestions. 
**Pylint is not Black formatting nor import sorting.**

I hope that helps! :)

**Comment by R0merol** [comment]
> Whoops 🤦, I forgot to mention @R0merol, I updated the ./code directory to ./src. If you would like me to revert it, please let me know. It may help with https://github.com/R0merol/Number-Game-v0.1/issues/9.

Oh yea, about that. Does using src instead of code the standard way of doing it? If so, then I'll switch to src. Also, regarding the lining, I might have to move this to a test branch to see how it works first

**Comment by colderinit** [comment]
From my experience, using src is pretty standard. Although it's really up to you, I used it in my code because it stands for source. 
The pylint won't actually affect the game running, but I agree with testing it! Pylint works wonders for pythonistas! I'll check up on the pr in ~8 hrs. (Unless it's ready 😄) I think we may have a time zone difference.

**Comment by R0merol** [comment]
Can you resolve the conflicts first? Thank you

**Comment by colderinit** [comment]
Sure! I'll revert to 'code' instead of 'src'. That seemed to be the only conflict.

**Comment by R0merol** [comment]
Actually, you can keep it as src. I'm planning on converting it to that name anyways

**Comment by colderinit** [comment]
Ok. I think that is the conflict. Your branch is 'code' but my branch is 'src'.

**Comment by colderinit** [comment]
I think i fixed the readme thing. It’s just the directory thing. Are you going to change the directory name on your branch?

**Comment by R0merol** [comment]
Yes, go ahead and change it

**Comment by colderinit** [comment]
I don’t have access to your branch. For the merge conflict to go away, I either have to change my branch to `code` or you have to change your branch to `src`. ( I think ) 😅 It’s a little confusing.

**Comment by R0merol** [comment]
Okay, just change it to code for now. Just make sure the conflict is resolved so I can merge it

**Comment by colderinit** [comment]
Awesome work my friend! I love your game! 😄

**Pull request merged**
